# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: matef <marvin@42.fr>                       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/11/08 17:43:23 by matef             #+#    #+#              #
#    Updated: 2021/11/08 17:43:28 by matef            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

DIR: /
FILES :
	ft_atoi \
	ft_bzero \
    ft_calloc \
	ft_isalnum \
	ft_isalpha \
	ft_isascii \
	ft_isdigit \
	isprint \
	ft_itoa \
    ft_memchr \
	ft_memcmp \
    ft_memcpy \
    ft_memmove \
    ft_memset \
    ft_putchar_fd \
    ft_putendl_fd \
    ft_putnbr_fd \
    ft_putstr_fd \
	ft_split \
	ft_strchr \
	ft_strdup \
    ft_striteri \
	ft_strjoin \
	strlcat \
	ft_strlcpy \
	ft_strlen \
	ft_strmapi \
	ft_strncmp \
	ft_strstr \
	ft_strrchr \
	ft_strtrim \
	ft_substr \
	ft_toupper \

cc: gcc
flags: -Wall -Wextra -Werror
clean: rm -r files

fclean:

re:
ar: ar -cvq libft.a *.o